config/routes.rb
Atshitshi::Application.routes.draw do
  resources :businesses

  

  get 'static_pages/home'

  get  'map' => 'map#index'
  post 'map' => 'map#index'
  get  'map/:search_value' => 'map#view'

  root to: 'map#index'
end

app/models/business.rb
class Business
  include Mongoid::Document
  include Mongoid::Geospatial

  field :name, type: String
  field :description, type: String
  field :location, type: Point
  field :street_number, type: String
  field :route, type: String
  field :locality, type: String
  field :administrative_area_level_1, type: String
  field :administrative_area_level_2, type: String
  field :country, type: String
  field :postal_code, type: String
  field :phone1, type: String
  field :phone2, type: String
  field :website, type: String

  spatial_index :location
  geo_field :location

  def street_name
    return self.route
  end

  def street_name=(val)
    self.route = val
  end

  def city
    return self.locality
  end

  def city=(val)
    self.locality = val
  end

  def state
    return self.administrative_area_level_1
  end

  def state=(val)
    self.administrative_area_level_1 = val
  end

  def county
    return self.administrative_area_level_2
  end

  def county=(val)
    self.administrative_area_level_2 = val
  end

  def lng
    return (!self.location.blank? && self.location[0]) || nil
  end

  def lng=(val)
    self.location = [ val, self.lat ]
  end

  def lat
    return (!self.location.blank? && self.location[1]) || nil
  end

  def lat=(val)
    self.location = [ self.lng, val ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render action: 'show', status: :created, location: @business }
      else
        format.html { render action: 'new' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :description, :location, :street_number, :route, :locality, :administrative_area_level_1, :administrative_area_level_2, :country, :postal_code, :phone1, :phone2, :website, :street_name, :city, :state, :county, :lng, :lat)
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
	before_filter :get_request_location

	def get_request_location
		@user_location = request.location
	end

	def index
		@user_search = params[:user_search]
		unless @user_search.blank? then
			# @user_location = 
		end
	end

	def search
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_filter :get_request_location
	def get_request_location
		@request_location = request.location
	end

	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/businesses/_form.html.slim
= form_for @business do |f|
  - if @business.errors.any?
    #error_explanation
      h2 = "#{pluralize(@business.errors.count, "error")} prohibited this business from being saved:"
      ul
        - @business.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label 'Address'
    = text_field_tag 'business_address_picker'
  .field
    = f.label :longitude
    = f.text_field :lng
  .field
    = f.label :latitude
    = f.text_field :lat
  .field
    = f.label :street_number
    = f.text_field :street_number
  .field
    = f.label :street_name
    = f.text_field :street_name
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :county
    = f.text_field :county
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :postal_code
    = f.text_field :postal_code
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :phone1
    = f.text_field :phone1
  .field
    = f.label :phone2
    = f.text_field :phone2
  .field
    = f.label :website
    = f.text_field :website
  .actions = f.submit 'Save'

app/views/businesses/edit.html.slim
h1 Editing business

== render 'form'

= link_to 'Show', @business
'|
= link_to 'Back', businesses_path

app/views/businesses/index.html.slim
h1 Listing businesses

table
  tr
    th Name
    th Description
    th Location
    th Street Number
    th Street Name
    th City
    th State
    th Zip
    th Phone1
    th Phone2
    th Website
    th
    th
    th

  - @businesses.each do |business|
    tr
      td = business.name
      td = business.description
      td = business.location
      td = business.street_number
      td = business.street_name
      td = business.city
      td = business.state
      td = business.postal_code
      td = business.phone1
      td = business.phone2
      td = business.website
      td = link_to 'Show', business
      td = link_to 'Edit', edit_business_path(business)
      td = link_to 'Destroy', business, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Business', new_business_path

app/views/businesses/new.html.slim
h1 New business

== render 'form'

= link_to 'Back', businesses_path

app/views/businesses/show.html.slim
p#notice = notice

p
  strong Name:
  = @business.name
p
  strong Description:
  = @business.description
p
  strong Location:
  = @business.location
p
  strong Street Number:
  = @business.street_number
p
  strong Street Name:
  = @business.street_name
p
  strong City:
  = @business.city
p
  strong State:
  = @business.state
p
  strong Zip:
  = @business.postal_code
p
  strong Phone1:
  = @business.phone1
p
  strong Phone2:
  = @business.phone2
p
  strong Website:
  = @business.website

= link_to 'Edit', edit_business_path(@business)
'|
= link_to 'Back', businesses_path

app/views/layouts/application.html.slim
doctype html
html
    head
        title = 'Atshitshi'
        = stylesheet_link_tag 'application', media: 'all'
        = javascript_include_tag 'application'
        = csrf_meta_tags
        script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"
    body
        div id="blanket"
        div id="map"
        == yield

app/views/layouts/businesses.html.slim
doctype html
html
    head
        title = 'Weed Mapper'
        meta name="viewport" content="width=device-width, initial-scale=1.0"
        script src="http://maps.google.com/maps/api/js?sensor=false"
        = stylesheet_link_tag 'application', media: 'all'
        = javascript_include_tag 'application'
        = csrf_meta_tags
    body
        == yield
        footer

app/views/layouts/map.html.slim
doctype html
html
    head
        title = 'Atshitshi'
        script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"
        = stylesheet_link_tag 'application', media: 'all'
        = javascript_include_tag 'application'
        = csrf_meta_tags
    body
        div id="blanket"
        div id="map"
        == yield

app/views/map/index.html.slim
/ h1 hello
div id="search_controls" title="Dialog Title"
	= form_tag :remote => true
		= label_tag 'Where?'
		= text_field_tag 'user_search', @user_search
		= submit_tag 'Go'
		= hidden_field_tag 'lat'
		= hidden_field_tag 'lng'
		= hidden_field_tag 'street_number'
		= hidden_field_tag 'route'
		= hidden_field_tag 'locality'
		= hidden_field_tag 'administrative_area_level_1'
		= hidden_field_tag 'administrative_area_level_2'
		= hidden_field_tag 'country'
		= hidden_field_tag 'postal_code'
		= hidden_field_tag 'type'
		= text_area_tag 'geocode'

javascript:
	$(document).ready(function() {
		user_location = '#{@user_location}';
	})

app/views/static_pages/home.html.slim
/ h1 hello
div id="search_controls" title="Dialog Title"
	= form_tag :remote => true
		= label_tag 'Where?'
		= text_field_tag 'user_location'
		= submit_tag 'Go'

javascript:
	$(document).ready(function() {
		request_location = '#{@request_location}';
	})